"""
EXTRACT SCHEMA: SQL Server -> SQLite
--------------------------------------
Run this ONCE on your machine (where SQL Server is running).
It reads your VaultX_DB structure and writes out `sqlite_schema.sql`,
a ready-to-use SQLite CREATE TABLE script.

Usage:
    python extract_schema.py

Requires: pyodbc (already in your requirements.txt)
"""

import pyodbc

# Same connection info your app already uses. Adjust DATABASE if needed.
CONN_STR = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=VaultX_DB;"
    "Trusted_Connection=yes"
)

# SQL Server type -> SQLite type
TYPE_MAP = {
    "int": "INTEGER",
    "bigint": "INTEGER",
    "smallint": "INTEGER",
    "tinyint": "INTEGER",
    "bit": "INTEGER",          # 0/1
    "varchar": "TEXT",
    "nvarchar": "TEXT",
    "char": "TEXT",
    "nchar": "TEXT",
    "text": "TEXT",
    "ntext": "TEXT",
    "datetime": "TEXT",        # store ISO8601 strings
    "datetime2": "TEXT",
    "date": "TEXT",
    "time": "TEXT",
    "float": "REAL",
    "real": "REAL",
    "decimal": "REAL",
    "numeric": "REAL",
    "varbinary": "BLOB",
    "binary": "BLOB",
    "image": "BLOB",
    "uniqueidentifier": "TEXT",
}


def get_tables(cursor):
    cursor.execute("""
        SELECT TABLE_NAME
        FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_TYPE = 'BASE TABLE'
        ORDER BY TABLE_NAME
    """)
    return [row[0] for row in cursor.fetchall()]


def get_columns(cursor, table):
    cursor.execute("""
        SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT,
               COLUMNPROPERTY(OBJECT_ID(?), COLUMN_NAME, 'IsIdentity') AS IS_IDENTITY
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = ?
        ORDER BY ORDINAL_POSITION
    """, (table, table))
    return cursor.fetchall()


def get_primary_key(cursor, table):
    cursor.execute("""
        SELECT KU.COLUMN_NAME
        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
        JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KU
          ON TC.CONSTRAINT_NAME = KU.CONSTRAINT_NAME
        WHERE TC.CONSTRAINT_TYPE = 'PRIMARY KEY' AND TC.TABLE_NAME = ?
    """, (table,))
    return [row[0] for row in cursor.fetchall()]


def get_foreign_keys(cursor, table):
    cursor.execute("""
        SELECT
            fk.name AS fk_name,
            c1.name AS column_name,
            t2.name AS ref_table,
            c2.name AS ref_column
        FROM sys.foreign_keys fk
        JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
        JOIN sys.tables t1 ON fk.parent_object_id = t1.object_id
        JOIN sys.tables t2 ON fk.referenced_object_id = t2.object_id
        JOIN sys.columns c1 ON fkc.parent_object_id = c1.object_id AND fkc.parent_column_id = c1.column_id
        JOIN sys.columns c2 ON fkc.referenced_object_id = c2.object_id AND fkc.referenced_column_id = c2.column_id
        WHERE t1.name = ?
    """, (table,))
    return cursor.fetchall()


def build_sqlite_ddl(table, columns, pk_cols, fk_rows):
    lines = []
    col_defs = []

    for col_name, data_type, is_nullable, default, is_identity in columns:
        sqlite_type = TYPE_MAP.get(data_type.lower(), "TEXT")
        parts = [f'"{col_name}"', sqlite_type]

        # Single-column integer primary key + identity -> SQLite autoincrement pattern
        if is_identity and col_name in pk_cols and len(pk_cols) == 1 and sqlite_type == "INTEGER":
            parts = [f'"{col_name}"', "INTEGER PRIMARY KEY AUTOINCREMENT"]
            col_defs.append(" ".join(parts))
            continue

        if is_nullable == "NO":
            parts.append("NOT NULL")

        col_defs.append(" ".join(parts))

    # If PK wasn't handled inline (composite key or non-identity), add separately
    handled_inline = len(pk_cols) == 1 and any("AUTOINCREMENT" in c for c in col_defs)
    if pk_cols and not handled_inline:
        col_defs.append(f'PRIMARY KEY ({", ".join(pk_cols)})')

    for fk_name, col, ref_table, ref_col in fk_rows:
        col_defs.append(f'FOREIGN KEY ("{col}") REFERENCES "{ref_table}"("{ref_col}")')

    lines.append(f'CREATE TABLE IF NOT EXISTS "{table}" (')
    lines.append(",\n".join(f"    {c}" for c in col_defs))
    lines.append(");")
    return "\n".join(lines)


def main():
    print("Connecting to SQL Server...")
    conn = pyodbc.connect(CONN_STR)
    cursor = conn.cursor()
    print("Connected. Reading schema...\n")

    tables = get_tables(cursor)
    output_sql = ["-- Auto-generated SQLite schema for VaultX_DB", "-- Generated by extract_schema.py", ""]

    for table in tables:
        print(f"  -> {table}")
        columns = get_columns(cursor, table)
        pk_cols = get_primary_key(cursor, table)
        fk_rows = get_foreign_keys(cursor, table)
        ddl = build_sqlite_ddl(table, columns, pk_cols, fk_rows)
        output_sql.append(ddl)
        output_sql.append("")

    with open("sqlite_schema.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(output_sql))

    conn.close()
    print(f"\nDone. Wrote {len(tables)} tables to sqlite_schema.sql")
    print("Please review this file before we use it — some SQL Server-specific")
    print("defaults (like GETDATE()) or constraints may need a manual touch-up.")


if __name__ == "__main__":
    main()